### login

POST http://localhost/car-nameplate/login.php
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### data

GET http://localhost/car-nameplate/data.php
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3QiLCJleHAiOjE1ODk1NTI1ODksInVzZXJuYW1lIjoidGVzdCJ9.N7gVU75BNSjxrSPPjBU-bLaUbUuFlMP3YHHq5-vGr5s