### login

POST http://localhost/car-nameplate/login.php
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### data

GET http://localhost/car-nameplate/data.php
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2Nhci1uYW1lcGxhdGUiLCJleHAiOjMyODAzMDcwNTYsInVzZXJuYW1lIjoidGVzdCJ9.HzNWHOVHpT_GCsUPBLyk90YrDAIDh5VWKPfbD_AY1Tw